title: Proyecto VPN con Raspberry Pi
email: framcoty322@gmail.com
description: Acceso remoto con WireGuard y red segmentada para pentesting.
baseurl: "" # Mantenerlo vacío para GitHub Pages raíz
url: "https://framcoty322.github.io"
github_username: framcoty322

permalink: /:title

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
